spring:
  datasource:
    username: rootxxxxxxxxxxxxxxcccccccccccccccccc
    password: rootxxxxxxxxxxxxxxcccccccccccccccccc
    driver-class-name: "com.mysql.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/aaa
